site_url: https://thelonelylands.com
display_url: https://thelonelylands.com

backend:
  name: git-gateway
  branch: master

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: entries
    label: Entries
    folder: content/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: "title"
    preview_path: posts/{{slug}}
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list", default: ["essay"]}
      - {label: "Body", name: "body", widget: "markdown"}